//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSManagemantDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T00000
    {
        public int T_LOGING_ID { get; set; }
        public string T_USER_ID { get; set; }
        public string T_PASSWORD { get; set; }
        public string T_ROLE { get; set; }
        public string T_USER_TYPE { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPDATE_USER { get; set; }
        public Nullable<System.DateTime> T_UPDATE_DATE { get; set; }
    }
}
