//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSManagemantDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T12005
    {
        public int T_PRICE_ID { get; set; }
        public Nullable<int> T_PACK_ID { get; set; }
        public Nullable<decimal> T_PURCHASE_PRICE { get; set; }
        public Nullable<int> T_SALE_PRICE_IN_BOX { get; set; }
        public Nullable<int> T_SALE_PRICE_IN_PIECE { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPDATE_USER { get; set; }
        public Nullable<System.DateTime> T_UPDATE_DATE { get; set; }
    }
}
